pull_request_rules:
  - name: greet contributors
    conditions:
      - -closed
      - author != ironmossvictim
    actions:
      comment:
        message: |
          Thanks @{{author}} for the contribution!

          Your description:

          {{body}}
